version: '3'
services:
  discovery-server:
    container_name: discovery-server
    build: ./discovery-server
    image: discovery-server
    ports:
      - 8761:8761
    networks:
      - microservices-network

  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ECommerce
    ports:
      - "5432:5432"
    networks:
      - microservices-network


  config-server:
    container_name: config-server
    build: ./config-server
    image: config-server
    volumes:
      - ./config:/var/config
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-server:8761/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8088/actuator/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - discovery-server
    ports:
      - 8088:8088
    networks:
      - microservices-network


  order-service:
    container_name: order-service
    build: ./order-service
    image: order-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-server:8761/eureka
        -SPRING_CONFIG_IMPORT=configserver:http://config-server:8088
    ports:
      - 8089:8089
    depends_on:
      config-server:
        condition: service_healthy
    networks:
       - microservices-network

  payment-service:
    container_name: payment-service
    build: ./payment-service
    image: payment-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-server:8761/eureka
        -SPRING_CONFIG_IMPORT=configserver:http://config-server:8088
    ports:
      - 8087:8087
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - microservices-network


  gateway-service:
    container_name: gateway-service
    build: ./gateway-service
    image: gateway-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-server:8761/eureka
        -SPRING_CONFIG_IMPORT=configserver:http://config-server:8088
    ports:
      - 8080:8080
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - microservices-network


networks:
  microservices-network:
    driver: bridge


