server:
  port: '8080'


management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  config:
    import: configserver:http://localhost:8088
    #import: configserver:http://config-server:8088
  application:
    name: GATEWAY-SERVICE
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
              - Path=/order/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
              - Path=/payment/**




eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      #defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true