server:
  port: '8087'


management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  config:
    import: configserver:http://localhost:8088
    #import: configserver:http://config-server:8088
  application:
    name: PAYMENT-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      #defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true