server:
  port: 8088


spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        native:
          #search-locations: /var/config
          search-locations: file:///D:/spring-boot-micro-services/MultiModuleApplication/config
      label: main

  profiles:
    active: default,native


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      #defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
